# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

conda:
   environment: docs/sora.yaml

# Build documentation in the docs/ directory with Sphinx
sphinx:
   builder: html
   configuration: docs/conf.py
   fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf
   - epub

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.7
   setup_py_install: true
   install:
   - requirements: docs/requirements.txt
   - method: pip
     path: .

# By default readthedocs does not checkout git submodules
submodules:                                                                                                                          
    include: all
